[options]
; Ruta de los módulos (el de la imagen base y el nuestro)
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Datos de conexión a la base de datos (se usan variables de entorno, pero aquí puedes dejarlos fijos si prefieres)
db_host = db
db_port = 5432
db_user = odoo
; db_password = ${POSTGRES_PASSWORD}
db_name = ${POSTGRES_DB:-postgres}

; Contraseña maestra para bases de datos
admin_passwd = ${ODOO_ADMIN_PASSWD}

; Nivel de log
log_level = info
log_handler = :INFO

; Otros parámetros opcionales
; without_demo = all
; list_db = True